Add salinity restoring file generation
COSIMA/om3-scripts pull request #36
Opened 2024-09-19 04:54 UTC by ezhilsabareesh8

This script processes and smooths sea water salinity data from the initial conditions NetCDF files generated using https://github.com/COSIMA/initial_conditions_access-om2 . It applies a uniform smoothing filter to the surface layer (0m depth) of the salinity for each month and concatenates the smoothed data into a single output NetCDF file.

2024-09-19 22:35 UTC, anton-seaice commented
Thanks @ezhilsabareesh8 - I will review soon.

I assume this uses the hh5 conda/analysis module ?

If you run _black_ on the script and commit the change, then the formatting test should pass.

From the Readme:

Python scripts are formatted using the [black formatter](https://github.com/psf/black). This is enforced using a github action running on pull requests. You will need to have pre-commit and black installed in your python environment. It is included in the conda/analysis enviornments in hh5, otherwise it can be installed through pip or conda. Then run `pre-commit install` once to ensure your commits have black run on them before committing.

2024-09-19 23:33 UTC, ezhilsabareesh8 commented
Thanks @anton-seaice, I just reformatted it using black.

2024-09-24 00:20 UTC, anton-seaice requested changes
Thanks @ezhilsabareesh8 

If you keep the data as an xarray object, it will save having to recreate all the attributes and dimensions etc. See the suggestions

2024-09-24 00:20 UTC, anton-seaice commented on salinity_restoring_generation/make_salt_sfc_restore_from_regridded_woa.py
> +    smoothed_data_np = np.stack(smoothed_monthly_data, axis=0)
```suggestion
salt_smoothed_da = xr.apply_ufunc(smooth2d, salt_da, input_core_dims=[['GRID_Y_T','GRID_X_T']], output_core_dims=[['GRID_Y_T','GRID_X_T']], vectorize=True, dask='parallelized')
```

2024-09-24 00:20 UTC, anton-seaice commented on salinity_restoring_generation/make_salt_sfc_restore_from_regridded_woa.py
> +    with nc.Dataset(output_file, "w", format="NETCDF4") as ncfile:
If you use xarray suggestions above, the only extra attributes you need are these (i think):

        salt_var.standard_name = "sea_water_salinity"
        salt_var.long_name = "Smoothed sea water salinity at level 0m"
        salt_var.units = "1"

you should just be able to set those and then say

salt_smoothed_da.to_netcdf()

2024-09-26 06:09 UTC, anton-seaice commented
Have a look now @ezhilsabareesh8 - this should work if we fix the time:units attribute in the source data

2024-09-30 05:20 UTC, anton-seaice commented on salinity_restoring_generation/make_salt_sfc_restore_from_regridded_woa.py
> +    file_template = f"{input_path}/woa23_ts_{{:02d}}_mom025.nc"
Can we generalise this line ? We will need to do this at three resolutions

2024-10-01 03:19 UTC, anton-seaice commented
This change will contribute to https://github.com/COSIMA/access-om3/issues/207

2024-10-01 03:21 UTC, anton-seaice commented
Lets park this until 

- [ ] https://github.com/COSIMA/initial_conditions_access-om2/issues/6 
- [ ] https://github.com/COSIMA/initial_conditions_access-om2/issues/7
- [ ] https://github.com/COSIMA/initial_conditions_access-om2/issues/3

are completed, and then we can finish this review.

2024-10-10 06:18 UTC, ezhilsabareesh8 commented
@anton-seaice I noticed that the time variable was changed to match the initial conditions, but the salinity restoring should actually begin at the middle of each month. In my original code, I had overwritten the time variable with:

```
times[:] = np.arange(0.5, 12.5, 1)  # Time values from 0.5 to 11.5
times.units = "months since 0001-01-01 00:00:00"
```

Could you please revert the changes made to the time variable in this commit [8b0c207](https://github.com/COSIMA/om3-scripts/pull/36/commits/8b0c2072da4a393070d5e64d770db1daca85ff6e)?

2025-05-22 04:43 UTC, anton-seaice commented
@ezhilsabareesh8 - I think this script should go in https://github.com/ACCESS-NRI/initial_conditions_access-om3/ ?

2025-06-16 06:59 UTC, anton-seaice commented
Hi @ezhilsabareesh8 

I pushed a couple of refinements to go with https://github.com/COSIMA/initial_conditions_access-om2/issues/6

This is the time coordinate now, which should be correct by cf-conventions and be the middle of the month

```
 time = 15.5, 45, 74.5, 105, 135.5, 166, 196.5, 227.5, 258, 288.5, 319, 349.5 ;

 double time(time) ;
                time:_FillValue = NaN ;
                time:standard_name = "time" ;
                time:long_name = "time" ;
                time:axis = "T" ;
                time:climatology = "climatology_bounds" ;
                time:units = "days since 1955-01-01" ;
                time:calendar = "gregorian" ;

```

I am running some tests now, can you see any issues ?

This is the diff between `/g/data/vk83/prerelease/configurations/inputs/access-om3/mom/surface_salt_restoring/global.25km/2025.01.30/salt_sfc_restore.nc` and my new one in January. Its bigger than expected, can that be explained by the changes we made to the initial conditions (e.g. 75 levels instead of 150 ?)

![image](https://github.com/user-attachments/assets/d6a85c39-9eb9-44da-9f58-d6da0ecc732c)

2025-06-17 02:25 UTC, ezhilsabareesh8 commented
There's no surface salinity difference between the old initial conditions `/g/data/vk83/prerelease/configurations/inputs/access-om3/mom/initial_conditions/global.25km/2025.03.19/ocean_temp_salt.res.nc` and new initial conditions `/g/data/vk83/prerelease/configurations/inputs/access-om3/mom/initial_conditions/global.25km/2025.06.17/ocean_temp_salt.res.nc`.

<img width="498" alt="Screenshot 2025-06-17 at 12 24 00 pm" src="https://github.com/user-attachments/assets/14b492f3-41fe-4731-afd3-c6d26d32a40f" />

2025-06-17 04:52 UTC, anton-seaice commented
Thanks - in the [25km](https://github.com/ACCESS-NRI/access-om3-configs/blob/202fa3cfe4d0491e8d09be56ae5881e218031a00/config.yaml#L27C7-L27C133) we are using the `2025.01.30` version of the salinity restoring still.

Looking at the `2025.01.30` initial conditions, it has 38 levels, and the top layer is at 1.083m, however in the new initial conditions, the top layer is at 0m. That's why we are seeing the difference. 

New-old, top layer:

![image](https://github.com/user-attachments/assets/e9dc98df-0af7-47f1-973f-c2a48c784fff)

New-old, 1.083m layer:
![image](https://github.com/user-attachments/assets/4b504107-8a5e-4faf-a5cb-fd593ab9646b)

If you are happy, feel free to merge this :)

2025-06-17 04:52 UTC, anton-seaice approved these changes

2025-06-17 04:55 UTC, anton-seaice commented
Oh I also ram the 25km for a year with the new salinity restore file and it appears to run ok

2025-06-19 01:01 UTC, merged